apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    # - on-demand
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
    # - arm64
  - key: karpenter.k8s.aws/instance.family
    operator: In
    values:
    - t2
    - t3
    - t3a
  - key: karpenter.k8s.aws/instance.size
    operator: NotIn
    values:
    - nano
    - micro
  # - key: node.kubernetes.io/instance-type
  #   operator: In
  #   values:
  #   # T3 family
  #   - t3.small
  #   - t3.medium
  #   - t3.large
  #   - t3.2xlarge
  # - key: topology.kubernetes.io/zone
  #   operator: In
  #   values:
  #   - us-east-1a
  #   - us-east-1b
  provider:
    securityGroupSelector:
      karpenter.sh/discovery: eks-demo
    subnetSelector:
      karpenter.sh/discovery: eks-demo
    amiFamily: AL2
    # instanceProfile: MyInstanceProfile
    # launchTemplate: MyLaunchTemplate
    tags:
      karpenter: "true"
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
