---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-EXAMPLE
spec:
  template:
    metadata:
      labels:
        team: my-team
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: nodeclass-EXAMPLE
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: eks.amazonaws.com/instance-category
        operator: In
        values:
        - t
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
