---
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: nodeclass-EXAMPLE
spec:
  ephemeralStorage:
    size: 30Gi
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  role: IAM-ROLE-NAME-EXAMPLE
  securityGroupSelectorTerms:
  - id: sg-EXAMPLE
  snatPolicy: Random
  subnetSelectorTerms:
  - id: subnet-EXAMPLE
  - id: subnet-EXAMPLE
