apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# Basic requirements:
# - To get Amazon 1.22 support, eksctl version should be >= 0.92.0
# - To get Amazon 1.23 support, eksctl version should be >= 0.109.0
# - To get Amazon 1.24 support, eksctl version should be >= 0.120.0
# - To get Amazon 1.25 support, eksctl version should be >= 0.132.0
# - To get Amazon 1.26 support, eksctl version should be >= 0.138.0
# - To get Amazon 1.27 support, eksctl version should be >= 0.143.0
metadata:
  name: eks-demo
  region: us-east-1
  version: "1.27"
  tags:
    karpenter.sh/discovery: eks-demo

# mind the known issues of `availabilityZones` if you are using eksctl 0.86.0:
# - https://github.com/weaveworks/eksctl/issues/4891
availabilityZones:
- us-east-1a
- us-east-1b

# privateCluster:
#   enabled: false

# kubernetesNetworkConfig:
#   ipFamily: IPv4
#   serviceIPv4CIDR: 10.100.0.0/16

vpc:
  cidr: 192.168.0.0/16
  publicAccessCIDRs: ["0.0.0.0/0"] # you should configured a proper CIDR list here
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)
  # autoAllocateIPv6: false
  # manageSharedNodeSecurityGroupRules: true
  # clusterEndpoints:
  #   privateAccess: false
  #   publicAccess: true

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    instanceTypes:
    - "t3a.medium"
    - "t3.medium"
    enableDetailedMonitoring: true
    privateNetworking: true
    disableIMDSv1: true
    spot: true
    ssh:
      allow: false
    # availabilityZones:
    # - us-east-1a
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      # - arn:aws:iam::aws:policy/AmazonSSMPatchAssociation

#   - name: customized-1
#     ami: ami-0b94943bd76cb55c2 # amazon-eks-node-1.27-v20230526, ref: https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html
#     amiFamily: AmazonLinux2
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     instanceTypes:
#     - "t3a.medium"
#     - "t3.medium"
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     spot: true
#     ssh:
#       allow: false
#     overrideBootstrapCommand: |
#       #!/bin/bash
#       /etc/eks/bootstrap.sh eks-demo --container-runtime containerd
#
#   - name: bottlerocket-1
#     amiFamily: Bottlerocket
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     instanceTypes:
#     - "t3a.medium"
#     - "t3.medium"
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     spot: true
#     bottlerocket:
#       enableAdminContainer: true
#       settings:
#         motd: "Hello, Bottlerocket ~!"
#         kubernetes:
#           cluster-certificate:
#           api-server:
#           cluster-dns-ip:
#           node-labels:
#           node-taints:

# nodeGroups:
#   - name: ng-1
#     amiFamily: AmazonLinux2
#     # instancePrefix: mixed
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     instancesDistribution:
#       capacityRebalance: false
#       instanceTypes:
#       - "t3a.medium"
#       - "t3.medium"
#       maxPrice: 0.0376 # t3a.medium
#       onDemandBaseCapacity: 0
#       onDemandPercentageAboveBaseCapacity: 50
#       # spotInstancePools: 2
#       spotAllocationStrategy: "capacity-optimized-prioritized"
#     containerRuntime: containerd
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     ssh:
#       allow: false

# fargateProfiles:
#   - name: karpenter
#     selectors:
#       - namespace: karpenter
#         labels:
#           app.kubernetes.io/name: karpenter

# addons:
#   - name: vpc-cni
#   - name: coredns
#   - name: kube-proxy

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
