apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
  # required eksctl 0.92.0 for Amazon EKS 1.22.
  # required eksctl 0.109.0 for Amazon EKS 1.23.
  version: "1.23"

fargateProfiles:
  - name: default
    selectors:
      - namespace: default
      - namespace: kube-system
    tags:
      fargate_profile: default
      cluster_name: eks-demo

# addons:
#   - name: vpc-cni
#   - name: coredns
#   - name: kube-proxy

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
