apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
  version: "1.21"

# mind the known issues of `availabilityZones` if you are using eksctl 0.86.0:
# - https://github.com/weaveworks/eksctl/issues/4891
availabilityZones:
- us-east-1a
- us-east-1b

privateCluster:
  enabled: false

vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  publicAccessCIDRs: ["0.0.0.0/0"] # you should configured a proper CIDR list here
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

kubernetesNetworkConfig:
  ipFamily: IPv4
  serviceIPv4CIDR: 10.100.0.0/16

iam:
  withOIDC: true

managedNodeGroups:
  - name: managed-1
    amiFamily: AmazonLinux2
    # instancePrefix: managed
    minSize: 2
    maxSize: 5
    volumeSize: 20
    instanceTypes:
    - "t3.small"
    # privateNetworking: true
    # releaseVersion: "1.21.5-20220226" ref: https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html
    # spot: true
    iam:
      withAddonPolicies:
        # hint: "albIngress" have be set as deprecated after 0.84.0
        # - https://github.com/weaveworks/eksctl/pull/4738
        # - https://github.com/weaveworks/eksctl/issues/4675
        # albIngress: true
        awsLoadBalancerController: true
        appMesh: true
        # appMeshPreview: true
        autoScaler: true
        certManager: true
        cloudWatch: true
        ebs: true
        # externalDNS: true
        # fsx: true
        # imageBuilder: true
        # xRay: true

cloudWatch:
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    # - "api"
    - "audit"
    # - "authenticator"
    # - "controllerManager"
    # - "scheduler"

# addons:
#   - name: vpc-cni
#   - name: coredns
#   - name: kube-proxy
