apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
  version: "1.23"

fargateProfiles:
  - name: karpenter
    selectors:
      - namespace: karpenter
        labels:
          app.kubernetes.io/name: karpenter
    tags:
      fargate: "true"
      fargate_profile: "karpenter"

  - name: kube-system-aws-load-balancer-controller
    selectors:
      - namespace: kube-system
        labels:
          app.kubernetes.io/name: aws-load-balancer-controller
    tags:
      fargate: "true"
      fargate_profile: "kube-system-aws-load-balancer-controller"

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
