apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
  # required eksctl 0.92.0 for Amazon EKS 1.22.
  # required eksctl 0.109.0 for Amazon EKS 1.23.
  version: "1.23"

availabilityZones:
- us-east-1a
- us-east-1b

vpc:
  cidr: 192.168.0.0/16
  publicAccessCIDRs: ["0.0.0.0/0"] # you should configured a proper CIDR list here
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    instanceTypes:
    - "t3.small"
    - "t3a.small"
    enableDetailedMonitoring: true
    privateNetworking: true
    disableIMDSv1: true
    spot: true
    ssh:
      allow: false

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
