apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-full
  region: us-east-1
  version: "1.34"
  tags:
    karpenter.sh/discovery: eks-demo-full

# mind the known issues of `availabilityZones` if you are using eksctl 0.86.0:
# - https://github.com/weaveworks/eksctl/issues/4891
availabilityZones:
- us-east-1a
- us-east-1b

privateCluster:
  enabled: false

kubernetesNetworkConfig:
  ipFamily: IPv4
  serviceIPv4CIDR: 10.100.0.0/16

vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)
  publicAccessCIDRs: # you should configured a proper CIDR list here
  - 0.0.0.0/0

accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
  bootstrapClusterCreatorAdminPermissions: true
  accessEntries: []
  # ref: https://eksctl.io/usage/access-entries/
  # - principalARN: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${TARGET_ROLE_NAME}
  #   accessPolicies:
  #   - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
  #     accessScope:
  #       type: cluster

autoModeConfig:
  enabled: true
  nodePools: []
  # - general-purpose
  # - system

iam:
  # Required eksctl v0.206.0
  # - https://github.com/eksctl-io/eksctl/releases/tag/v0.206.0
  withOIDC: true
  # podIdentityAssociations:
  # - namespace: kube-system
  #   serviceAccountName: ebs-csi-controller-sa-self-managed
  #   roleName: pod-identity-role-for-ebs-csi-controller-self-managed
  #   permissionPolicyARNs:
  #     - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

managedNodeGroups:
  - name: mng-1
    amiFamily: AmazonLinux2023
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    volumeType: gp3
    instanceTypes:
    - "t3a.medium"
    - "t3.medium"
    enableDetailedMonitoring: true
    privateNetworking: true
    disableIMDSv1: true
    disablePodIMDS: false
    spot: true
    ssh:
      allow: false
    # availabilityZones:
    # - us-east-1a
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      # (Optional) Only required if you need "EC2 Instance Connect"
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      # (Optional) Only required if you are using "SSM"
      - arn:aws:iam::aws:policy/AmazonSSMPatchAssociation

#   - name: amazonlinux-1
#     # AWS CLI:
#     # $ aws ec2 describe-images --image-ids $(aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.34/amazon-linux-2023/x86_64/standard/recommended/image_id --query "Parameter.Value" --output text)
#     ami: ami-0ed77ff8dd0903035 # amazon-eks-node-al2023-x86_64-standard-1.34-v20250920, ref: https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html
#     amiFamily: AmazonLinux2023
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     volumeType: gp3
#     instanceTypes:
#     - "t3a.medium"
#     - "t3.medium"
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     disablePodIMDS: false
#     spot: true
#     ssh:
#       allow: false
#     overrideBootstrapCommand: |
#       #!/bin/bash
#       /etc/eks/bootstrap.sh eks-demo --container-runtime containerd
#
#   - name: bottlerocket-1
#     amiFamily: Bottlerocket
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     volumeType: gp3
#     instanceTypes:
#     - "t3a.medium"
#     - "t3.medium"
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     spot: true
#     bottlerocket:
#       enableAdminContainer: true
#       settings:
#         motd: "Hello, Bottlerocket ~!"
#         kubernetes:
#           cluster-certificate:
#           api-server:
#           cluster-dns-ip:
#           node-labels:
#           node-taints:

#   - name: mng-windows
#     amiFamily: WindowsServer2022FullContainer
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 50
#     volumeType: gp3
#     instanceTypes:
#     - "t3a.medium"
#     - "t3.medium"
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     disablePodIMDS: false
#     spot: true
#     ssh:
#       allow: false
#     iam:
#       attachPolicyARNs:
#       - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
#       - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
#       # (Optional) Only required if you need "EC2 Instance Connect"
#       - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
#       # (Optional) Only required if you are using "SSM"
#       - arn:aws:iam::aws:policy/AmazonSSMPatchAssociation

# nodeGroups:
#   - name: ng-1
#     amiFamily: AmazonLinux2023
#     # instancePrefix: mixed
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     volumeType: gp3
#     instancesDistribution:
#       capacityRebalance: false
#       instanceTypes:
#       - "t3a.medium"
#       - "t3.medium"
#       maxPrice: 0.0376 # t3a.medium
#       onDemandBaseCapacity: 0
#       onDemandPercentageAboveBaseCapacity: 50
#       # spotInstancePools: 2
#       spotAllocationStrategy: "capacity-optimized-prioritized"
#     containerRuntime: containerd
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     disablePodIMDS: false
#     ssh:
#       allow: false

# fargateProfiles:
#   - name: karpenter
#     selectors:
#       - namespace: kube-system
#         labels:
#           app.kubernetes.io/name: karpenter

addonsConfig:
  # - https://docs.aws.amazon.com/eks/latest/eksctl/pod-identity-associations.html
  autoApplyPodIdentityAssociations: false

addons:
  - name: kube-proxy
    version: latest
  - name: vpc-cni
    version: latest
    podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: aws-node
      permissionPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: eks-pod-identity-agent
    version: latest
  - name: metrics-server
    version: latest
  - name: aws-network-flow-monitoring-agent
    version: latest
    podIdentityAssociations:
    - namespace: amazon-network-flow-monitor
      serviceAccountName: aws-network-flow-monitor-agent-service-account
      permissionPolicyARNs:
      - arn:aws:iam::aws:policy/CloudWatchNetworkFlowMonitorAgentPublishPolicy
  - name: amazon-cloudwatch-observability
    version: latest
    podIdentityAssociations:
    - namespace: amazon-cloudwatch
      serviceAccountName: cloudwatch-agent
      permissionPolicyARNs:
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
  - name: aws-ebs-csi-driver
    version: latest
    podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: ebs-csi-controller-sa
      permissionPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
