apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
  version: "1.21"

availabilityZones:
- us-east-1a
- us-east-1b

privateCluster:
  enabled: false

vpc:
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

iam:
  withOIDC: true

managedNodeGroups:
  - name: managed-1
    amiFamily: AmazonLinux2
    # instancePrefix: managed
    minSize: 2
    maxSize: 5
    volumeSize: 20
    instanceTypes:
    - "t3.medium"
    # releaseVersion: "1.21.5-20220123"
    iam:
      withAddonPolicies:
        albIngress: true
        appMesh: true
        # appMeshPreview: true
        autoScaler: true
        certManager: true
        cloudWatch: true
        ebs: true
        # externalDNS: true
        # fsx: true
        # imageBuilder: true
        # xRay: true
    # spot: true
    # privateNetworking: true
