apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-ipv6
  region: us-east-1
  version: "1.26"
  tags:
    karpenter.sh/discovery: eks-demo

availabilityZones:
- us-east-1a
- us-east-1b

kubernetesNetworkConfig:
  ipFamily: IPv6

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    instanceTypes:
    - "t3a.small"
    - "t3a.medium"
    enableDetailedMonitoring: true
    privateNetworking: true
    disableIMDSv1: true
    spot: true
    ssh:
      allow: false

addons:
  - name: kube-proxy
  - name: vpc-cni
  - name: coredns

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
