apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
  # required eksctl 0.92.0 for Amazon EKS 1.22.
  # required eksctl 0.109.0 for Amazon EKS 1.23.
  version: "1.23"

# mind the known issues of `availabilityZones` if you are using eksctl 0.86.0:
# - https://github.com/weaveworks/eksctl/issues/4891
availabilityZones:
- us-east-1a
- us-east-1b

# privateCluster:
#   enabled: false

# kubernetesNetworkConfig:
#   ipFamily: IPv4
#   serviceIPv4CIDR: 10.100.0.0/16

vpc:
  cidr: 192.168.0.0/16
  publicAccessCIDRs: ["0.0.0.0/0"] # you should configured a proper CIDR list here
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)
  # autoAllocateIPv6: false
  # manageSharedNodeSecurityGroupRules: true
  # clusterEndpoints:
  #   privateAccess: false
  #   publicAccess: true

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    instanceTypes:
    - "t3.small"
    - "t3a.small"
    enableDetailedMonitoring: true
    privateNetworking: true
    disableIMDSv1: true
    spot: true
    ssh:
      allow: false

#   - name: containerd-1
#     ami: ami-028df9f7b798ba67e # amazon-eks-node-1.23-v20220811, ref: https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html
#     amiFamily: AmazonLinux2
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     instanceTypes:
#     - "t3.small"
#     - "t3a.small"
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     spot: true
#     ssh:
#       allow: false
#     overrideBootstrapCommand: |
#       #!/bin/bash
#       /etc/eks/bootstrap.sh eks-demo --container-runtime containerd
#
#   - name: bottlerocker-1
#     amiFamily: Bottlerocket
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     instanceTypes:
#     - "t3.small"
#     - "t3a.small"
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     spot: true
#     bottlerocket:
#       enableAdminContainer: true
#       settings:
#         motd: "Hello, Bottlerocket ~!"
#         kubernetes
#           cluster-certificate:
#           api-server:
#           cluster-dns-ip:
#           node-labels:
#           node-taints:
#
# nodeGroups:
#   - name: ng-1
#     instanceType: t3.small
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     amiFamily: AmazonLinux2
#     containerRuntime: containerd
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     ssh:
#       allow: false
#
#   - name: ng-mixed-1
#     amiFamily: AmazonLinux2
#     # instancePrefix: mixed
#     minSize: 2
#     maxSize: 5
#     desiredCapacity: 2
#     volumeSize: 30
#     instancesDistribution:
#       capacityRebalance: false
#       instanceTypes:
#       - "t3.small"
#       - "t3a.small"
#       maxPrice: 0.015
#       onDemandBaseCapacity: 0
#       onDemandPercentageAboveBaseCapacity: 50
#       # spotInstancePools: 2
#       spotAllocationStrategy: "capacity-optimized-prioritized"
#     containerRuntime: containerd
#     enableDetailedMonitoring: true
#     privateNetworking: true
#     disableIMDSv1: true
#     ssh:
#       allow: false

# fargateProfiles:
#   - name: fp-1
#     selectors:
#       - namespace: default
#       - namespace: kube-system
#       - namespace: my-namespace
#         labels:
#           run-with-fargate: "true"

# addons:
#   - name: vpc-cni
#   - name: coredns
#   - name: kube-proxy

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
