apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-only
  region: us-east-1
  version: "1.22"

fargateProfiles:
  - name: default
    selectors:
      - namespace: default
      - namespace: kube-system

cloudWatch:
  clusterLogging:
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
