apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1
  version: "1.25"

availabilityZones:
- us-east-1a
- us-east-1b

vpc:
  cidr: 192.168.0.0/16
  publicAccessCIDRs: ["0.0.0.0/0"]
  nat:
    gateway: HighlyAvailable

iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    instanceTypes:
    - "t3a.small"
    - "t3a.medium"
    enableDetailedMonitoring: true
    privateNetworking: true
    disableIMDSv1: true
    spot: true
    ssh:
      allow: false

fargateProfiles:
  - name: karpenter
    selectors:
      - namespace: karpenter
        labels:
          app.kubernetes.io/name: karpenter

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
