apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-ipv6
  region: us-east-1
  version: "1.33"
  # tags:
  #   karpenter.sh/discovery: eks-demo-ipv6

availabilityZones:
- us-east-1a
- us-east-1b

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true

kubernetesNetworkConfig:
  ipFamily: IPv6

accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
  bootstrapClusterCreatorAdminPermissions: true

iam:
  # Required eksctl v0.206.0
  # - https://github.com/eksctl-io/eksctl/releases/tag/v0.206.0
  withOIDC: true

managedNodeGroups:
  - name: mng-1
    amiFamily: AmazonLinux2023
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 30
    volumeType: gp3
    instanceTypes:
    - "t3a.medium"
    - "t3.medium"
    enableDetailedMonitoring: true
    privateNetworking: true
    disableIMDSv1: true
    disablePodIMDS: false
    spot: true
    ssh:
      allow: false

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
  - name: kube-proxy
    version: latest
  - name: vpc-cni
    version: latest
    # "ec2:AssignIpv6Addresses" would be required for IPv6 cluster
    # - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/iam-policy.md#ipv6-mode
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "ec2:AssignIpv6Addresses"
        - "ec2:DescribeInstances"
        - "ec2:DescribeTags"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DescribeInstanceTypes"
        Resource: '*'
      - Effect: Allow
        Action:
        - "ec2:CreateTags"
        Resource: 'arn:aws:ec2:*:*:network-interface/*'
  - name: coredns
    version: latest
  - name: eks-pod-identity-agent
    version: latest
  - name: metrics-server
    version: latest

cloudWatch:
  # ref: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
  clusterLogging:
    logRetentionInDays: 90
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
